server: 
  appname: dompet-kilat
  version: 1.0.0
  appkey: 
  port: 8000
  env: development 

jwt: 
  secret: secretkey

database:
  dbhost: mongo_db
  dbuser:
  dbport: 27017
  dbpass:
  dbname: dompet-kilat
  dbprovider: mongodb
  dbssl: disable
  dbtz: Asia/Jakarta
  db_automigrate: true